apiVersion: batch/v1
kind: Job
metadata:
  name: pos-backend-migrate
spec:
  template:
    spec:
      containers:
        - name: migrate
          image: ghcr.io/zerotechmn/pos-backend:latest
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
      restartPolicy: OnFailure
