# Generated by Django 5.0.2 on 2025-07-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
