# Generated by Django 5.0.2 on 2025-07-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_user_token_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Terminal Name')),
                ('terminal_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Terminal id')),
                ('terminal_pos_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Terminal id')),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='MAC Address')),
                ('ip_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Hardware unique id')),
                ('guur_user', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Guur user')),
                ('application_version', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Application version')),
                ('tbd_application_version', models.CharField(blank=True, max_length=1000, null=True, verbose_name='TDB Application version')),
                ('tdb_terminal_id', models.CharField(blank=True, max_length=1000, null=True, verbose_name='TDB Terminal number')),
                ('pts_ip_address', models.CharField(blank=True, max_length=1000, null=True, verbose_name='PTS IP Address')),
                ('client_version', models.CharField(default='', max_length=50, verbose_name='Version')),
                ('client_agent', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Client OS')),
                ('client_ip', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'POS Terminal',
            },
        ),
    ]
